package clinicapptts;


import ADDFORMSINTERNALPAGE.userinfo;
import user.*;
import admin.*;
import static clinicapptts.Registration.passwordhashing;
import config.Session;

import config.dbConnector;
import doctors.doctor_dashboard;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author once
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    } 
    
    static String name;
      public static String loginAccRole (String username,String Password){
           dbConnector connect = new dbConnector();
    try{
         String hashingpass = passwordhashing(Password);  
      String sql ="SELECT * FROM tbl_userdetails WHERE u_username = '"+username+"' AND u_password = '"+hashingpass+"'";
      ResultSet rs = connect.getData(sql);
     if(rs.next()){
         Session sess = Session.getInstance();
         sess.setId(rs.getInt("u_id"));
         sess.setFname(rs.getString("u_firstname"));
         sess.setLname(rs.getString("u_lastname"));
         sess.setEmail(rs.getString("u_email"));
         sess.setUname(rs.getString("u_username"));
         sess.setType(rs.getString("u_account"));
          sess.setStatus(rs.getString("u_status"));
         sess.setPass(rs.getString("u_password"));
         
        
         return rs.getString("u_account");
     }else{
         return null;
     }
     
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "DataBase Connection Error");
        return null;
    }
       }
      public static String loginAccStatus (String username,String Password){
           dbConnector connect = new dbConnector();
    try{
         String hashingpass = passwordhashing(Password);  
      String sql ="SELECT u_status FROM tbl_userdetails WHERE u_username = '"+username+"' AND u_password = '"+hashingpass+"'";
      ResultSet rs = connect.getData(sql);
     if(rs.next()){
         return rs.getString("u_status");
     }else{
         return null;
     }
     
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "DataBase Connection Error");
        return null;
    }
       }
      
      
      
      
      
      
      
       Color navcolor = new Color(0,204,204);
    Color bodycolor = new Color(153,204,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        userPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        SIGNIN = new javax.swing.JPanel();
        signinButton = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        creatAccount = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicapptts/login.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/resizebg.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("CLINIC APPOINTMENT ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 190, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Tracker System");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        userName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Username:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        jPanel2.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 40));

        userPass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        userPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassActionPerformed(evt);
            }
        });
        jPanel2.add(userPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 210, 40));

        jLabel9.setText("Forgot password?");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, 20));

        SIGNIN.setBackground(new java.awt.Color(0, 204, 204));
        SIGNIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SIGNIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGNINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SIGNINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SIGNINMouseExited(evt);
            }
        });
        SIGNIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signinButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        signinButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signinButton.setText("SIGN IN");
        signinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinButtonMouseExited(evt);
            }
        });
        SIGNIN.add(signinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jPanel2.add(SIGNIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 130, 30));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        creatAccount.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        creatAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creatAccount.setText("Create account");
        creatAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatAccountMouseClicked(evt);
            }
        });
        jPanel9.add(creatAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 120, 20));

        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel2.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 320));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("LOGIN");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLINIC");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 270, 60));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/clinicCare-removebg-preview (1).png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 320));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, 320));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CARE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 30, 230, 60));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 290, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassActionPerformed

    private void signinButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseEntered
       signinButton.setBackground(navcolor);
    }//GEN-LAST:event_signinButtonMouseEntered

    private void SIGNINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNINMouseEntered
       SIGNIN.setBackground(navcolor);
    }//GEN-LAST:event_SIGNINMouseEntered

    private void SIGNINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNINMouseExited
         SIGNIN.setBackground(navcolor);
    }//GEN-LAST:event_SIGNINMouseExited

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
            if(showpass.isSelected()){
                userPass.setEchoChar((char)0);
            }else{
                userPass.setEchoChar('*');
            }
    }//GEN-LAST:event_showpassActionPerformed

    private void SIGNINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNINMouseClicked
     
    }//GEN-LAST:event_SIGNINMouseClicked

    private void signinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseClicked
    String accountrole =loginAccRole (userName.getText(),userPass.getText());
    
    if(accountrole != null ){
    String accountstatus =loginAccStatus (userName.getText(),userPass.getText());
    
        if(accountrole.equals("Admin")){
            JOptionPane.showMessageDialog(null,"Login Success!"); 
          Admin_dashboard adminDash = new Admin_dashboard();
            adminDash.setVisible(true);
//            adminDash.Name.setText(""+name);
            this.dispose();
        }else if(accountrole.equals("DOCTOR")){
        if(accountstatus.equals("Active")){
         JOptionPane.showMessageDialog(null,"Login Success!");
         
             doctor_dashboard docDash = new doctor_dashboard();
            docDash.setVisible(true);
//            docDash.Name.setText(""+name);
            
            this.dispose();
         }else{
         JOptionPane.showMessageDialog(null,"Account is inactive!");
       }
        
       }else if(accountrole.equals("DESK")){
       if(accountstatus.equals("Active")){
         JOptionPane.showMessageDialog(null,"Login Success!");
         
            desk_dashboard deskDash = new desk_dashboard();
            deskDash.setVisible(true);
//            deskDash.Name.setText(""+name);
            
            this.dispose();
         }else{
         JOptionPane.showMessageDialog(null,"Account is inactive!");
              }
            
         }else{
            JOptionPane.showMessageDialog(null,"Invalid Account");
         } 
    }else{
        JOptionPane.showMessageDialog(null,"Invalid Username or Password");
    }
    }//GEN-LAST:event_signinButtonMouseClicked

    private void signinButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseExited
       signinButton.setBackground(bodycolor);
    }//GEN-LAST:event_signinButtonMouseExited

    private void creatAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatAccountMouseClicked
     Registration register = new Registration();
     register.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_creatAccountMouseClicked

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SIGNIN;
    private javax.swing.JLabel creatAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JLabel signinButton;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPass;
    // End of variables declaration//GEN-END:variables
}
