package user;


import clinicapptts.LoginForm;
import java.awt.Color;
import javax.swing.JOptionPane;


public class desk_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form desk_dashboard
     */
    public desk_dashboard() {
        initComponents();
    }
    Color navcolor = new Color(0,204,204);
    Color bodycolor = new Color(153,204,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NAV = new javax.swing.JPanel();
        DASHBOARD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PATIENT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        APPOINTMENT = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CALENDAR = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DOCTOR = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        REPORTS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JPanel();
        LAGOUTBUTTON = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAV.setBackground(new java.awt.Color(0, 204, 204));
        NAV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        NAV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DASHBOARD.setBackground(new java.awt.Color(0, 204, 204));
        DASHBOARD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DASHBOARDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DASHBOARDMouseExited(evt);
            }
        });
        DASHBOARD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        DASHBOARD.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 190, 40));

        NAV.add(DASHBOARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 40));

        PATIENT.setBackground(new java.awt.Color(0, 204, 204));
        PATIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PATIENTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PATIENTMouseExited(evt);
            }
        });
        PATIENT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/group_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel2.setText("PATIENTS");
        PATIENT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        NAV.add(PATIENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 40));

        APPOINTMENT.setBackground(new java.awt.Color(0, 204, 204));
        APPOINTMENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                APPOINTMENTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                APPOINTMENTMouseExited(evt);
            }
        });
        APPOINTMENT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/icons8-appointment-48.png"))); // NOI18N
        jLabel3.setText("APPOINTMENTS");
        APPOINTMENT.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        NAV.add(APPOINTMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 40));

        CALENDAR.setBackground(new java.awt.Color(0, 204, 204));
        CALENDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CALENDARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CALENDARMouseExited(evt);
            }
        });
        CALENDAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/calendar_month_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel4.setText("CALENDAR");
        CALENDAR.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        NAV.add(CALENDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 40));

        DOCTOR.setBackground(new java.awt.Color(0, 204, 204));
        DOCTOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DOCTORMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DOCTORMouseExited(evt);
            }
        });
        DOCTOR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/icons8-doctor-48.png"))); // NOI18N
        jLabel5.setText("DOCTORS");
        DOCTOR.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        NAV.add(DOCTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 190, 40));

        REPORTS.setBackground(new java.awt.Color(0, 204, 204));
        REPORTS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REPORTSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                REPORTSMouseExited(evt);
            }
        });
        REPORTS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/icons8-business-report-48.png"))); // NOI18N
        jLabel6.setText("REPORTS");
        REPORTS.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 40));

        NAV.add(REPORTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 40));

        LOGOUT.setBackground(new java.awt.Color(0, 204, 204));
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUTMouseExited(evt);
            }
        });
        LOGOUT.setLayout(null);

        LAGOUTBUTTON.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LAGOUTBUTTON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LAGOUTBUTTON.setText("SIGN OUT");
        LAGOUTBUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LAGOUTBUTTONMouseClicked(evt);
            }
        });
        LOGOUT.add(LAGOUTBUTTON);
        LAGOUTBUTTON.setBounds(0, 10, 120, 20);

        NAV.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 120, 40));

        jPanel1.add(NAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 530));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 680, 40));

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 680, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DASHBOARDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHBOARDMouseEntered
        DASHBOARD.setBackground(bodycolor);
    }//GEN-LAST:event_DASHBOARDMouseEntered

    private void DASHBOARDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHBOARDMouseExited
        DASHBOARD.setBackground(navcolor);
    }//GEN-LAST:event_DASHBOARDMouseExited

    private void PATIENTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PATIENTMouseEntered
        PATIENT.setBackground(bodycolor);
    }//GEN-LAST:event_PATIENTMouseEntered

    private void PATIENTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PATIENTMouseExited
       PATIENT.setBackground(navcolor);
    }//GEN-LAST:event_PATIENTMouseExited

    private void APPOINTMENTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APPOINTMENTMouseEntered
       APPOINTMENT.setBackground(bodycolor);
    }//GEN-LAST:event_APPOINTMENTMouseEntered

    private void APPOINTMENTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APPOINTMENTMouseExited
        APPOINTMENT.setBackground(navcolor);
    }//GEN-LAST:event_APPOINTMENTMouseExited

    private void CALENDARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALENDARMouseEntered
        CALENDAR.setBackground(bodycolor);
    }//GEN-LAST:event_CALENDARMouseEntered

    private void CALENDARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CALENDARMouseExited
        CALENDAR.setBackground(navcolor);
    }//GEN-LAST:event_CALENDARMouseExited

    private void DOCTORMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOCTORMouseEntered
       DOCTOR.setBackground(bodycolor);
    }//GEN-LAST:event_DOCTORMouseEntered

    private void DOCTORMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOCTORMouseExited
        DOCTOR.setBackground(navcolor);
    }//GEN-LAST:event_DOCTORMouseExited

    private void REPORTSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REPORTSMouseEntered
       REPORTS.setBackground(bodycolor);
    }//GEN-LAST:event_REPORTSMouseEntered

    private void REPORTSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REPORTSMouseExited
        REPORTS.setBackground(navcolor);
    }//GEN-LAST:event_REPORTSMouseExited

    private void LOGOUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseEntered
        LOGOUT.setBackground(bodycolor);
    }//GEN-LAST:event_LOGOUTMouseEntered

    private void LOGOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseExited
        LOGOUT.setBackground(navcolor);
    }//GEN-LAST:event_LOGOUTMouseExited

    private void LAGOUTBUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAGOUTBUTTONMouseClicked
         LoginForm LForm = new LoginForm();
       LForm.setVisible(true);
       this.dispose();
       JOptionPane.showMessageDialog(null,"Signout successfully");
    }//GEN-LAST:event_LAGOUTBUTTONMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desk_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desk_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desk_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desk_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desk_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel APPOINTMENT;
    private javax.swing.JPanel CALENDAR;
    private javax.swing.JPanel DASHBOARD;
    private javax.swing.JPanel DOCTOR;
    private javax.swing.JLabel LAGOUTBUTTON;
    private javax.swing.JPanel LOGOUT;
    private javax.swing.JPanel NAV;
    private javax.swing.JPanel PATIENT;
    private javax.swing.JPanel REPORTS;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
