/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADDFORMSINTERNALPAGE;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author NoName
 */
public class patientform extends javax.swing.JInternalFrame {

    /**
     * Creates new form patientform
     */
    public patientform() {
        initComponents();
        
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        middlename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        malebutton = new javax.swing.JRadioButton();
        femalebutton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SAVEbutton = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cancelbutton = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        address = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Firstname:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 20, 80, 16);
        jPanel2.add(fname);
        fname.setBounds(120, 10, 180, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Middlename:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 60, 90, 16);
        jPanel2.add(middlename);
        middlename.setBounds(120, 50, 180, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lastname:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 90, 16);
        jPanel2.add(lname);
        lname.setBounds(120, 90, 180, 30);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gender:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 140, 60, 20);

        malebutton.setText("MALE");
        jPanel2.add(malebutton);
        malebutton.setBounds(120, 140, 60, 23);

        femalebutton.setText("FEMALE");
        femalebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(femalebutton);
        femalebutton.setBounds(200, 140, 93, 23);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contact No.:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(350, 120, 80, 16);
        jPanel2.add(contact);
        contact.setBounds(440, 110, 190, 30);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Note :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 200, 60, 16);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Date of Birth:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(340, 20, 90, 20);

        SAVEbutton.setBackground(new java.awt.Color(0, 204, 204));
        SAVEbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SAVEbutton.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SAVE");
        SAVEbutton.add(jLabel16);
        jLabel16.setBounds(0, 0, 80, 30);

        jPanel2.add(SAVEbutton);
        SAVEbutton.setBounds(410, 300, 80, 30);

        cancelbutton.setBackground(new java.awt.Color(0, 204, 204));
        cancelbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelbutton.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("CANCEL");
        cancelbutton.add(jLabel17);
        jLabel17.setBounds(0, 0, 90, 30);

        jPanel2.add(cancelbutton);
        cancelbutton.setBounds(520, 300, 90, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 370, 130);
        jPanel2.add(address);
        address.setBounds(440, 60, 190, 30);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Address:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(370, 60, 60, 30);

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanel2.add(jFormattedTextField3);
        jFormattedTextField3.setBounds(440, 10, 190, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 650, 360);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW PATIENT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 320, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femalebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femalebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SAVEbutton;
    private javax.swing.JTextField address;
    private javax.swing.JPanel cancelbutton;
    private javax.swing.JTextField contact;
    private javax.swing.JRadioButton femalebutton;
    private javax.swing.JTextField fname;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton malebutton;
    private javax.swing.JTextField middlename;
    // End of variables declaration//GEN-END:variables
}
