/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADDFORMSINTERNALPAGE;

import java.awt.Color;

/**
 *
 * @author once
 */
public class patientViewinfo extends javax.swing.JFrame {

    /**
     * Creates new form patientViewinfo
     */
    public patientViewinfo() {
        initComponents();
    }
    Color navcolor = new Color(0,204,204);
    Color bodycolor = new Color(153,204,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pfname = new javax.swing.JLabel();
        plname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pAge = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pGender = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pBirthdate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pContact = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pAddress = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Diagnosis = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        dfname = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dlname = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        demail = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        PRINTBUT = new javax.swing.JPanel();
        refresh = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        pfname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pfname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pfname);
        pfname.setBounds(120, 50, 130, 20);

        plname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        plname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(plname);
        plname.setBounds(120, 80, 130, 20);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Age:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 100, 50, 20);

        pAge.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pAge.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pAge);
        pAge.setBounds(120, 100, 130, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Gender: ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 130, 80, 20);

        pGender.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pGender.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pGender);
        pGender.setBounds(120, 130, 130, 20);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Birthdate:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 160, 80, 20);

        pBirthdate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pBirthdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pBirthdate);
        pBirthdate.setBounds(120, 160, 130, 20);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Contact:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 190, 80, 20);

        pContact.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pContact);
        pContact.setBounds(120, 190, 130, 20);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setText("Address:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 220, 80, 20);

        pAddress.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pAddress);
        pAddress.setBounds(120, 220, 130, 20);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel15.setText("PATIENT DIAGNOSIS");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 290, 220, 30);

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel16.setText("PATIENT INFORMATION");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 10, 250, 30);

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel18.setText("DIAGNOSIS:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(40, 340, 130, 16);

        Diagnosis.setEditable(false);
        Diagnosis.setColumns(20);
        Diagnosis.setRows(5);
        Diagnosis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane2.setViewportView(Diagnosis);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 360, 550, 160);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setText("Firstname:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(320, 60, 90, 20);

        dfname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dfname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(dfname);
        dfname.setBounds(430, 60, 160, 20);

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel21.setText("Lastname:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(320, 90, 90, 20);

        dlname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dlname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(dlname);
        dlname.setBounds(430, 90, 160, 20);

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel23.setText("Email:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(320, 120, 90, 20);

        demail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        demail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(demail);
        demail.setBounds(430, 120, 160, 20);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel25.setText("Date check:");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(300, 330, 110, 20);

        date.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        date.setText("jLabel1");
        date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(date);
        date.setBounds(410, 330, 130, 20);

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel27.setText("DOCTOR INFORMATION");
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel27);
        jLabel27.setBounds(330, 10, 250, 30);

        PRINTBUT.setBackground(new java.awt.Color(0, 204, 204));
        PRINTBUT.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        PRINTBUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PRINTBUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PRINTBUTMouseExited(evt);
            }
        });
        PRINTBUT.setLayout(null);

        refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refresh.setText("PRINT");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        PRINTBUT.add(refresh);
        refresh.setBounds(10, 0, 70, 30);

        jPanel2.add(PRINTBUT);
        PRINTBUT.setBounds(470, 540, 90, 30);

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel20.setText("Firstname:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 50, 90, 20);

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel22.setText("Lastname:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(20, 70, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 50, 600, 580);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImage/arrow_circle_left_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel28);
        jLabel28.setBounds(6, 4, 60, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        //        displaydata();
    }//GEN-LAST:event_refreshMouseClicked

    private void PRINTBUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTBUTMouseEntered
        PRINTBUT.setBackground(bodycolor);
    }//GEN-LAST:event_PRINTBUTMouseEntered

    private void PRINTBUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTBUTMouseExited
        PRINTBUT.setBackground(navcolor);
    }//GEN-LAST:event_PRINTBUTMouseExited

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        //         desk_dashboard dashB = new desk_dashboard();
        //       dashB.setVisible(true);
        //        reports_dash dashreports = new reports_dash();
        //       dashB.maindesktop.add(dashreports).setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jLabel28MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientViewinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientViewinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientViewinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientViewinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientViewinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Diagnosis;
    private javax.swing.JPanel PRINTBUT;
    public javax.swing.JLabel date;
    public javax.swing.JLabel demail;
    public javax.swing.JLabel dfname;
    public javax.swing.JLabel dlname;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel pAddress;
    public javax.swing.JLabel pAge;
    public javax.swing.JLabel pBirthdate;
    public javax.swing.JLabel pContact;
    public javax.swing.JLabel pGender;
    public javax.swing.JLabel pfname;
    public javax.swing.JLabel plname;
    private javax.swing.JLabel refresh;
    // End of variables declaration//GEN-END:variables
}
