/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnector;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author once
 */
public class editform extends javax.swing.JFrame {

    /**
     * Creates new form editform
     */
    public editform() {
        initComponents();
    }

     Color navcolor = new Color(0,204,204);
       Color bodycolor = new Color(153,204,255);
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        savepanel = new javax.swing.JPanel();
        savebutton = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        updatebut = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        u_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Status:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 70, 50, 30);

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select status", "Active", "Inactive" }));
        status.setToolTipText("");
        status.setName(""); // NOI18N
        jPanel2.add(status);
        status.setBounds(130, 70, 170, 30);
        status.getAccessibleContext().setAccessibleName("");

        savepanel.setBackground(new java.awt.Color(0, 204, 204));
        savepanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        savepanel.setLayout(null);

        savebutton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        savebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savebutton.setText("SAVE");
        savepanel.add(savebutton);
        savebutton.setBounds(4, 4, 90, 20);

        jPanel2.add(savepanel);
        savepanel.setBounds(160, 150, 0, 30);

        update.setBackground(new java.awt.Color(0, 204, 204));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(null);

        updatebut.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        updatebut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatebut.setText("Update");
        updatebut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebutMouseClicked(evt);
            }
        });
        update.add(updatebut);
        updatebut.setBounds(10, 0, 60, 30);

        jPanel2.add(update);
        update.setBounds(120, 150, 80, 30);

        cancel.setBackground(new java.awt.Color(0, 204, 204));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cancel");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        cancel.add(jLabel6);
        jLabel6.setBounds(10, 0, 60, 30);

        jPanel2.add(cancel);
        cancel.setBounds(230, 150, 80, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User ID:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 30, 70, 30);

        u_id.setEnabled(false);
        jPanel2.add(u_id);
        u_id.setBounds(130, 30, 170, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 60, 380, 420);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Update Account status and password");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 390, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(bodycolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(bodycolor);
        
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
         cancel.setBackground(navcolor);
    }//GEN-LAST:event_cancelMouseExited

    private void updatebutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebutMouseClicked
//         if(!newpass.getText().equals(confirmpass.getText())){
//              JOptionPane.showMessageDialog(null, "Password doesn't Match!"); 
//               newpass.setText("");
//               confirmpass.setText("");
//               return;
//               
//         }else if(newpass.getText().length()<8){  
//               JOptionPane.showMessageDialog(null, "Password must atleast 8 characters!"); 
//              
//         }else{
        dbConnector dbc = new dbConnector();
            boolean result = dbc.insertData("UPDATE tbl_userdetails SET u_status = '"+status.getSelectedItem()+"'Where u_id = '"+u_id.getText()+"'");
            
             JOptionPane.showMessageDialog(null,"Successfully Updated!");
           
            userlist ulist = new userlist();
            ulist.setVisible(true);
            this.dispose();
         
           
    }//GEN-LAST:event_updatebutMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       userlist ulist = new userlist();
       ulist.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel savebutton;
    private javax.swing.JPanel savepanel;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JTextField u_id;
    private javax.swing.JPanel update;
    private javax.swing.JLabel updatebut;
    // End of variables declaration//GEN-END:variables
}
